library(epical)
shinydata <- read.csv("/home/ins-bio/R/metadata_shiny.csv")
shinydata <- add_epi_week(shinydata, "date", system = "cdc")
shinydata$Date <- epi_week_date(shinydata$epi_week, shinydata$epi_year,system = "cdc")
write.csv(shinydata, "/home/fascue/Documents/Git/metadata_shiny.csv")
colnames(shinydata)
data <- read.csv("/home/fascue/Documents/Git/metadata_shiny.csv")
str(data)

unique(data$VOC.VOI)
